import 'dart:convert';

import 'package:desafio_covid/app/repositories/continent_repository.dart';
import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';

class DioMock extends Mock implements Dio {}

main() {
  final dio = DioMock();
  final repository = ContinentRepository(dio);
  test(
    'deve trazer uma lista',
    () async {
      when(dio.get(any))
          .thenAnswer((_) async => Response(data: jsonDecode(jsonData)));
      final list = await repository.fetchContinents();
      print(list[0].active);
      expect(list[0].cases, 32588946);
    },
  );
}

String jsonData = '''
[
  {
    "updated": 1618580314478,
    "cases": 32588946,
    "todayCases": 371896,
    "deaths": 458540,
    "todayDeaths": 2724,
    "recovered": 28638980,
    "todayRecovered": 234839,
    "active": 3491426,
    "critical": 28756,
    "casesPerOneMillion": 7029.34,
    "deathsPerOneMillion": 98.91,
    "tests": 715837990,
    "testsPerOneMillion": 154404.17,
    "population": 4636131183,
    "continent": "Asia",
    "activePerOneMillion": 753.09,
    "recoveredPerOneMillion": 6177.34,
    "criticalPerOneMillion": 6.2,
    "continentInfo": {
      "lat": 23.7027273,
      "long": 62.3750637
    },
    "countries": [
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Bahrain",
      "Bangladesh",
      "Bhutan",
      "Brunei",
      "Cambodia",
      "China",
      "Cyprus",
      "Georgia",
      "Hong Kong",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Israel",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kuwait",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Lebanon",
      "Macao",
      "Malaysia",
      "Maldives",
      "Mongolia",
      "Myanmar",
      "Nepal",
      "Oman",
      "Pakistan",
      "Palestine",
      "Philippines",
      "Qatar",
      "S. Korea",
      "Saudi Arabia",
      "Singapore",
      "Sri Lanka",
      "Syrian Arab Republic",
      "Taiwan",
      "Tajikistan",
      "Thailand",
      "Timor-Leste",
      "Turkey",
      "UAE",
      "Uzbekistan",
      "Vietnam",
      "Yemen"
    ]
  },
  {
    "updated": 1618580314479,
    "cases": 37184687,
    "todayCases": 95950,
    "deaths": 842974,
    "todayDeaths": 1568,
    "recovered": 28861089,
    "todayRecovered": 87842,
    "active": 7480624,
    "critical": 17031,
    "casesPerOneMillion": 62733.46,
    "deathsPerOneMillion": 1422.16,
    "tests": 473146626,
    "testsPerOneMillion": 798235.13,
    "population": 592740923,
    "continent": "North America",
    "activePerOneMillion": 12620.39,
    "recoveredPerOneMillion": 48690.9,
    "criticalPerOneMillion": 28.73,
    "continentInfo": {
      "lat": 31.6768272,
      "long": -146.4707474
    },
    "countries": [
      "Anguilla",
      "Antigua and Barbuda",
      "Aruba",
      "Bahamas",
      "Barbados",
      "Belize",
      "Bermuda",
      "British Virgin Islands",
      "Canada",
      "Caribbean Netherlands",
      "Cayman Islands",
      "Costa Rica",
      "Cuba",
      "Curaçao",
      "Dominica",
      "Dominican Republic",
      "El Salvador",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guatemala",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Martinique",
      "Mexico",
      "Montserrat",
      "Nicaragua",
      "Panama",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Martin",
      "Saint Pierre Miquelon",
      "Saint Vincent and the Grenadines",
      "Sint Maarten",
      "St. Barth",
      "Trinidad and Tobago",
      "Turks and Caicos Islands",
      "USA"
    ]
  },
  {
    "updated": 1618580314480,
    "cases": 23032855,
    "todayCases": 157527,
    "deaths": 612233,
    "todayDeaths": 5376,
    "recovered": 20650543,
    "todayRecovered": 122764,
    "active": 1770079,
    "critical": 24358,
    "casesPerOneMillion": 53125.44,
    "deathsPerOneMillion": 1412.12,
    "tests": 82996170,
    "testsPerOneMillion": 191431.23,
    "population": 433556063,
    "continent": "South America",
    "activePerOneMillion": 4082.7,
    "recoveredPerOneMillion": 47630.62,
    "criticalPerOneMillion": 56.18,
    "continentInfo": {
      "lat": -15.6551563,
      "long": -100.7484231
    },
    "countries": [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Falkland Islands (Malvinas)",
      "French Guiana",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela"
    ]
  },
  {
    "updated": 1618580314482,
    "cases": 42373011,
    "todayCases": 206864,
    "deaths": 966613,
    "todayDeaths": 3866,
    "recovered": 36606596,
    "todayRecovered": 155169,
    "active": 4799802,
    "critical": 32929,
    "casesPerOneMillion": 56649.4,
    "deathsPerOneMillion": 1292.29,
    "tests": 694525945,
    "testsPerOneMillion": 928526.82,
    "population": 747986948,
    "continent": "Europe",
    "activePerOneMillion": 6416.96,
    "recoveredPerOneMillion": 48940.15,
    "criticalPerOneMillion": 44.02,
    "continentInfo": {
      "lat": 25.771324,
      "long": -35.6012256
    },
    "countries": [
      "Albania",
      "Andorra",
      "Austria",
      "Belarus",
      "Belgium",
      "Bosnia",
      "Bulgaria",
      "Channel Islands",
      "Croatia",
      "Czechia",
      "Denmark",
      "Estonia",
      "Faroe Islands",
      "Finland",
      "France",
      "Germany",
      "Gibraltar",
      "Greece",
      "Holy See (Vatican City State)",
      "Hungary",
      "Iceland",
      "Ireland",
      "Isle of Man",
      "Italy",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macedonia",
      "Malta",
      "Moldova",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "San Marino",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "UK",
      "Ukraine"
    ]
  },
  {
    "updated": 1618580314483,
    "cases": 4433974,
    "todayCases": 12678,
    "deaths": 117363,
    "todayDeaths": 313,
    "recovered": 3963106,
    "todayRecovered": 8882,
    "active": 353505,
    "critical": 3812,
    "casesPerOneMillion": 3246.7,
    "deathsPerOneMillion": 85.94,
    "tests": 42568461,
    "testsPerOneMillion": 31169.99,
    "population": 1365687329,
    "continent": "Africa",
    "activePerOneMillion": 258.85,
    "recoveredPerOneMillion": 2901.91,
    "criticalPerOneMillion": 2.79,
    "continentInfo": {
      "lat": 1.7383867,
      "long": -16.3094636
    },
    "countries": [
      "Algeria",
      "Angola",
      "Benin",
      "Botswana",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Comoros",
      "Congo",
      "Côte d'Ivoire",
      "DRC",
      "Djibouti",
      "Egypt",
      "Equatorial Guinea",
      "Eritrea",
      "Ethiopia",
      "Gabon",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libyan Arab Jamahiriya",
      "Madagascar",
      "Malawi",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Rwanda",
      "Réunion",
      "Sao Tome and Principe",
      "Senegal",
      "Seychelles",
      "Sierra Leone",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Sudan",
      "Swaziland",
      "Tanzania",
      "Togo",
      "Tunisia",
      "Uganda",
      "Western Sahara",
      "Zambia",
      "Zimbabwe"
    ]
  },
  {
    "updated": 1618580314484,
    "cases": 60585,
    "todayCases": 233,
    "deaths": 1166,
    "todayDeaths": 11,
    "recovered": 34729,
    "todayRecovered": 7,
    "active": 24690,
    "critical": 4,
    "casesPerOneMillion": 1419.36,
    "deathsPerOneMillion": 27.32,
    "tests": 18405609,
    "testsPerOneMillion": 431198.99,
    "population": 42684722,
    "continent": "Australia/Oceania",
    "activePerOneMillion": 578.43,
    "recoveredPerOneMillion": 813.62,
    "criticalPerOneMillion": 0.09,
    "continentInfo": {
      "lat": -8.6599161,
      "long": 91.1469847
    },
    "countries": [
      "Australia",
      "Fiji",
      "French Polynesia",
      "Marshall Islands",
      "Micronesia",
      "New Caledonia",
      "New Zealand",
      "Papua New Guinea",
      "Samoa",
      "Solomon Islands",
      "Vanuatu",
      "Wallis and Futuna"
    ]
  }
]
''';
